### ISSUE TITLE
where is join-command.sh ?

### ISSUE THREAD

**Issue by runalsh** [kunchalavikram1427/kubernetes_using_kubeadm_with_terraform_on_aws#1]
join-command.sh  is absent in the repository

**Comment by kunchalavikram1427** [comment]
Let me check

**Comment by kunchalavikram1427** [comment]
It will be created by master.sh file. Look at the end contents of that file.

**Comment by kunchalavikram1427** [comment]
It will be created by master.sh file. Look at the end contents of that file.
